### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by UHD630** [LeaguePrank/LeagueTeamBoost#2]
已开启管理员模式

第一次打开软件 如果处于无限火力选人阶段 点击查看状态 会提示当前模式支持战斗福利
但点击TEAMBOOST按钮 会提示 请确保现在客户端处于无限火力选人阶段再使用软件
之后再点击查看状态  都显示不支持解锁了

**Comment by MarioCrane** [comment]
腾讯把接口关了，国服用不了了
